name: tests-orders

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g yarn
      - run: cd orders && yarn install && yarn run test:ci
